//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ForumHomepage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ForumHomepage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Plugin.ForumHomepage", typeof(ForumHomepage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        internal static System.CodeDom.MemberAttributes AxWebBrowser1_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("AxWebBrowser1.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool AxWebBrowser1_Locked {
            get {
                object obj = ResourceManager.GetObject("AxWebBrowser1.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        internal static System.CodeDom.MemberAttributes AxWebBrowser1_Modifiers {
            get {
                object obj = ResourceManager.GetObject("AxWebBrowser1.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Object similar to System.Windows.Forms.AxHost+State.
        /// </summary>
        internal static object AxWebBrowser1_OcxState {
            get {
                object obj = ResourceManager.GetObject("AxWebBrowser1.OcxState", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        internal static System.CodeDom.MemberAttributes cmdNavigate_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("cmdNavigate.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cmdNavigate_Image {
            get {
                object obj = ResourceManager.GetObject("cmdNavigate.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool cmdNavigate_Locked {
            get {
                object obj = ResourceManager.GetObject("cmdNavigate.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        internal static System.CodeDom.MemberAttributes cmdNavigate_Modifiers {
            get {
                object obj = ResourceManager.GetObject("cmdNavigate.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        internal static System.CodeDom.MemberAttributes pnlNavBar_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("pnlNavBar.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool pnlNavBar_DrawGrid {
            get {
                object obj = ResourceManager.GetObject("pnlNavBar.DrawGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=8, Height=8}.
        /// </summary>
        internal static System.Drawing.Size pnlNavBar_GridSize {
            get {
                object obj = ResourceManager.GetObject("pnlNavBar.GridSize", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool pnlNavBar_Locked {
            get {
                object obj = ResourceManager.GetObject("pnlNavBar.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        internal static System.CodeDom.MemberAttributes pnlNavBar_Modifiers {
            get {
                object obj = ResourceManager.GetObject("pnlNavBar.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool pnlNavBar_SnapToGrid {
            get {
                object obj = ResourceManager.GetObject("pnlNavBar.SnapToGrid", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        internal static System.CodeDom.MemberAttributes txtURL_DefaultModifiers {
            get {
                object obj = ResourceManager.GetObject("txtURL.DefaultModifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to False.
        /// </summary>
        internal static bool txtURL_Locked {
            get {
                object obj = ResourceManager.GetObject("txtURL.Locked", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.CodeDom.MemberAttributes similar to Assembly.
        /// </summary>
        internal static System.CodeDom.MemberAttributes txtURL_Modifiers {
            get {
                object obj = ResourceManager.GetObject("txtURL.Modifiers", resourceCulture);
                return ((System.CodeDom.MemberAttributes)(obj));
            }
        }
    }
}
